spring:
  application:
    name: heima-ai


#  ai:
#    openai:
#      api-key: sk-7dfdb36729a84df39d890f04ffccd7b0
#      base-url: https://dashscope.aliyuncs.com/compatible-mode
#
#      chat:
#        options:
#          model: deepseek-v3.2
#          temperature: 0.7
  ai:
    ollama:
      base-url: http://localhost:11434
      chat:
        model: deepseek-r1:7b
  data:
    redis:
      host: localhost
      port: 6379
      database: 11
#屏蔽openai配置
  autoconfigure:
    exclude:
      - org.springframework.ai.autoconfigure.openai.OpenAiAutoConfiguration
logging:
  level:
    org.springframework.ai: debug
    com.itheima.ai: debug